CREATE TABLE category
(
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    category_name VARCHAR(255)                             NOT NULL,
    CONSTRAINT pk_category PRIMARY KEY (id)
);

ALTER TABLE category
    ADD CONSTRAINT uc_category_categoryname UNIQUE (category_name);