CREATE TABLE product
(
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    product_name VARCHAR(255)                             NOT NULL,
    measurement  VARCHAR(255)                             NOT NULL,
    unit_price   FLOAT                                    NOT NULL,
    category_id  INTEGER,
    CONSTRAINT pk_product PRIMARY KEY (id)
);

ALTER TABLE product
    ADD CONSTRAINT FK_PRODUCT_ON_CATEGORY FOREIGN KEY (category_id) REFERENCES category (id);