CREATE TABLE product_cart
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    product_id INTEGER,
    cart_id    INTEGER,
    amount     INTEGER                                  NOT NULL,
    sale_price FLOAT                                    NOT NULL,
    CONSTRAINT pk_productcart PRIMARY KEY (id)
);

ALTER TABLE product_cart
    ADD CONSTRAINT FK_PRODUCTCART_ON_CART FOREIGN KEY (cart_id) REFERENCES cart (id);

ALTER TABLE product_cart
    ADD CONSTRAINT FK_PRODUCTCART_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES product (id);