CREATE TABLE realized
(
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    type_payment INTEGER                                  NOT NULL,
    total_price  FLOAT                                    NOT NULL,
    CONSTRAINT pk_realized PRIMARY KEY (id)
);